    //Adding four numbers without parameter
function add (){
var Num1 =12;
var Num2 =14;
var Num3 =16;
var Num4 =18;
var NumResult = Num1 + Num2 + Num3 + Num4;
console.log(NumResult) 
};

add();


//Adding four numbers with parameter
function add(num1,num2,num3,num4){
  
  var NumResult = num1 + num2 + num3 + num4;
  console.log(NumResult)
  
}
  add(12,14,16,18);



// Adding odd numbers between 50-100.
function oddNumber(){
  for(var z=50; z<=100; z++){
    
    if(z%2!=0){
          console.log(z);
    }
    

    }}
    oddNumber();
    
